version: "3.8"

services:
  web:
    build: .
    container_name: devices-management
    ports:
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin123
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    volumes:
      - ./NA_Project:/app          # hot-reload kode (opsional di prod)
      - static_volume:/app/static
      - media_volume:/app/media
      - db_volume:/app/db          # path sesuai settings.py
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  db_volume:
