version: "3.8"

services:
  web:
    build: .
    container_name: devices-management
    ports:
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: admin      # boleh dihapus kalau sudah ada user
      DJANGO_SUPERUSER_PASSWORD: admin123
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    volumes:
      # Hot-reload kode (opsional di produksi)
      - ./NA_Project:/app
      # FILE database yang sudah berisi tabel — ini yang bikin “tanpa migrate” aman
      - ./NA_Project/db.sqlite3:/app/NA_Project/db.sqlite3
      # Direktori statik & media
      - static_volume:/app/static
      - media_volume:/app/media
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
