# Generated by Django 5.2.1 on 2025-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('distribution', 'customer')},
            },
        ),
    ]
