# Generated by Django 5.2.1 on 2025-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segmentation',
            options={'verbose_name': 'Segmentation', 'verbose_name_plural': 'Segmentations'},
        ),
        migrations.RenameField(
            model_name='segmentation',
            old_name='customer',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='segmentation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='segmentation_type',
            field=models.CharField(choices=[('distribution', 'Distribution'), ('customer', 'Customer')], default='distribution', max_length=20),
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='distribution',
        ),
    ]
