# Generated by Django 5.2.1 on 2025-05-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0003_rename_ssh_port_device_api_port_alter_device_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='api_port',
            new_name='ssh_port',
        ),
    ]
