# Generated by Django 5.2.1 on 2025-05-20 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0004_rename_api_port_device_ssh_port'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssh_port',
        ),
        migrations.AddField(
            model_name='device',
            name='api_port',
            field=models.PositiveIntegerField(default=25000),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(default='mikrotik', max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('Configure', 'Configure'), ('Verify', 'Verify'), ('Connect API', 'Connect API')], max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='messages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Error', 'Error')], max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
