# Generated by Django 5.2.1 on 2025-05-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0005_alter_log_options_remove_device_ssh_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='device',
            name='api_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
