# Generated by Django 5.2.1 on 2025-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0006_device_ssh_port_alter_device_api_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
