# Generated by Django 5.2.1 on 2025-05-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0007_alter_device_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='command',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='log',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
