# Generated by Django 5.2.1 on 2025-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0009_device_segmentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_category',
            field=models.CharField(choices=[('router_end_point', 'Router End Point'), ('router_failover', 'Router Failover'), ('radio_bts', 'Radio BTS'), ('radio_station', 'Radio Station'), ('router_bridging', 'Router Bridging')], default='router_end_point', max_length=30),
        ),
    ]
