# Generated by Django 5.2.1 on 2025-05-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0010_device_device_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('segmentation_type', models.CharField(choices=[('distribution', 'Distribution'), ('access', 'Access')], default='access', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='segmentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NA_Apps.segmentation'),
        ),
    ]
