# Generated by Django 5.2.1 on 2025-05-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0011_segmentation_alter_device_segmentation'),
        ('segmentation', '0002_alter_segmentation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='segmentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='segmentation.segmentation'),
        ),
        # migrations.DeleteModel(
        #     name='Segmentation',
        # ),
    ]
