# Generated by Django 5.2.1 on 2025-05-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),  # Add dependency on segmentation app
        ('NA_Apps', '0012_alter_device_segmentation_delete_segmentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='segmentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='segmentation.segmentation'),
        ),
    ]
