# Generated by Django 5.2.1 on 2025-05-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0012_fix_segmentation_foreign_key'),
        ('NA_Apps', '0013_auto_20250527_2333'),
    ]

    operations = [
    ]
