# Generated by Django 5.2.1 on 2025-06-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NA_Apps', '0014_merge_20250528_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Segmentation',
        ),
    ]
